name: Deploy Backend

on:
  push:
    branches:
      - developer
    paths:
      - 'backend/**'

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: [dev, prod]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: ./backend

      - name: Terraform Plan
        id: plan
        run: terraform plan -var-file=${{ matrix.environment }}.tfvars
        working-directory: ./backend

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve -var-file=${{ matrix.environment }}.tfvars
        working-directory: ./backend
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}