name: Deploy and Destroy Environments

on:
  push:
    branches:
      - developer  # Trigger on push to developer branch
    paths:
      - 'environments/**'
  pull_request:
    branches:
      - main  # Trigger on PR to main (prod deployment after approval)
  workflow_dispatch:  # Allow manual triggers for production deploy/destroy

concurrency:
  group: deploy-and-destroy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Deploy Dev on push to `developer`
  deploy-dev:
    if: github.ref == 'refs/heads/developer'  # Run only on developer branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          az --version

      - name: Run deploy.sh script
        run: bash deploy.sh
        working-directory: ./environments/infra
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

  # Deploy Prod on PR merge to `main`
  deploy-prod:
    if: github.event_name == 'pull_request' && github.base_ref == 'main'  # Run only on PR to main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          az --version

      - name: Run deploy.sh script
        run: bash deploy.sh
        working-directory: ./environments/infra
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

      - name: Wait for manual approval (Production Deploy)
        uses: hmarr/auto-approve-action@v3

  # Destroy Dev Infra (Manual Trigger)
  destroy-dev:
    if: github.event_name == 'workflow_dispatch'  # Run only on manual trigger
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          az --version

      - name: Run destroy.sh script
        run: bash destroy.sh
        working-directory: ./environments/infra
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

      - name: Wait for manual approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.token }}
          approvers: team-leads

  # Destroy Prod Infra (Manual Trigger)
  destroy-prod:
    if: github.event_name == 'workflow_dispatch'  # Run only on manual trigger
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          az --version

      - name: Run destroy.sh script
        run: bash destroy.sh
        working-directory: ./environments/infra
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

      - name: Wait for manual approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.token }}
          approvers: team-leads