name: Deploy Backend

on:
  push:
    branches:
      - developer  # Trigger on push to developer branch
    paths:
      - 'backend/**'
  pull_request:
    branches:
      - main  # Trigger on PR to main branch
    paths:
      - 'backend/**'

jobs:
  deploy-dev:
    if: github.ref == 'refs/heads/developer'  # Only run for developer branch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}  # Use the JSON credentials
          client-id: ${{ secrets.AZURE_CLIENT_ID }}  # Required for SERVICE_PRINCIPAL
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}  # Required for SERVICE_PRINCIPAL
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}  # Required for SERVICE_PRINCIPAL
          enable-AzPSSession: true  # Optional: Enable PowerShell session
      
      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: ./backend

      - name: Terraform Plan
        id: plan
        run: terraform plan -var-file=dev.tfvars
        working-directory: ./backend

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve -var-file=dev.tfvars
        working-directory: ./backend


  destroy:
    if: github.event_name == 'workflow_dispatch'  # Only run when manually triggered
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}  # Use the JSON credentials
          client-id: ${{ secrets.AZURE_CLIENT_ID }}  # Required for SERVICE_PRINCIPAL
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}  # Required for SERVICE_PRINCIPAL
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}  # Required for SERVICE_PRINCIPAL
          enable-AzPSSession: true  # Optional: Enable PowerShell session

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: ./backend

      - name: Terraform Plan for Destroy
        id: plan-destroy
        run: terraform plan -destroy -var-file=dev.tfvars
        working-directory: ./backend

      - name: Wait for manual approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.token }}
          approvers: team-leads  # Replace with your team's GitHub username or team name

      - name: Terraform Destroy
        id: destroy
        run: terraform destroy -auto-approve -var-file=dev.tfvars
        working-directory: ./backend