name: Deploy Dev and Prod

on:
  push:
    branches:
      - main
    paths:
      - 'environments/**'

jobs:
  deploy-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        id: init
        run: terraform init -backend-config="key=dev/terraform.tfstate"
        working-directory: ./environments/dev

      - name: Terraform Plan
        id: plan
        run: terraform plan -var-file=terraform.tfvars
        working-directory: ./environments/dev

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve -var-file=terraform.tfvars
        working-directory: ./environments/dev
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

  deploy-prod:
    runs-on: ubuntu-latest
    needs: deploy-dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        id: init
        run: terraform init -backend-config="key=prod/terraform.tfstate"
        working-directory: ./environments/prod

      - name: Terraform Plan
        id: plan
        run: terraform plan -var-file=terraform.tfvars
        working-directory: ./environments/prod

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve -var-file=terraform.tfvars
        working-directory: ./environments/prod
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}